//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Buddy : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Buddy(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Buddy obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Buddy obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Buddy() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_Buddy(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Buddy() : this(pjsua2PINVOKE.new_Buddy(), true) {
    SwigDirectorConnect();
  }

  public void create(Account acc, BuddyConfig cfg) {
    pjsua2PINVOKE.Buddy_create(swigCPtr, Account.getCPtr(acc), BuddyConfig.getCPtr(cfg));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isValid() {
    bool ret = pjsua2PINVOKE.Buddy_isValid(swigCPtr);
    return ret;
  }

  public int getId() {
    int ret = pjsua2PINVOKE.Buddy_getId(swigCPtr);
    return ret;
  }

  public BuddyInfo getInfo() {
    BuddyInfo ret = new BuddyInfo(pjsua2PINVOKE.Buddy_getInfo(swigCPtr), true);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void subscribePresence(bool subscribe) {
    pjsua2PINVOKE.Buddy_subscribePresence(swigCPtr, subscribe);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public void updatePresence() {
    pjsua2PINVOKE.Buddy_updatePresence(swigCPtr);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public void sendInstantMessage(SendInstantMessageParam prm) {
    pjsua2PINVOKE.Buddy_sendInstantMessage(swigCPtr, SendInstantMessageParam.getCPtr(prm));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public void sendTypingIndication(SendTypingIndicationParam prm) {
    pjsua2PINVOKE.Buddy_sendTypingIndication(swigCPtr, SendTypingIndicationParam.getCPtr(prm));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void onBuddyState() {
    if (SwigDerivedClassHasMethod("onBuddyState", swigMethodTypes0)) pjsua2PINVOKE.Buddy_onBuddyStateSwigExplicitBuddy(swigCPtr); else pjsua2PINVOKE.Buddy_onBuddyState(swigCPtr);
  }

  public virtual void onBuddyEvSubState(OnBuddyEvSubStateParam prm) {
    if (SwigDerivedClassHasMethod("onBuddyEvSubState", swigMethodTypes1)) pjsua2PINVOKE.Buddy_onBuddyEvSubStateSwigExplicitBuddy(swigCPtr, OnBuddyEvSubStateParam.getCPtr(prm)); else pjsua2PINVOKE.Buddy_onBuddyEvSubState(swigCPtr, OnBuddyEvSubStateParam.getCPtr(prm));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("onBuddyState", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateBuddy_0(SwigDirectorMethodonBuddyState);
    if (SwigDerivedClassHasMethod("onBuddyEvSubState", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateBuddy_1(SwigDirectorMethodonBuddyEvSubState);
    pjsua2PINVOKE.Buddy_director_connect(swigCPtr, swigDelegate0, swigDelegate1);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(Buddy))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

  private void SwigDirectorMethodonBuddyState() {
    onBuddyState();
  }

  private void SwigDirectorMethodonBuddyEvSubState(global::System.IntPtr prm) {
    onBuddyEvSubState(new OnBuddyEvSubStateParam(prm, false));
  }

  public delegate void SwigDelegateBuddy_0();
  public delegate void SwigDelegateBuddy_1(global::System.IntPtr prm);

  private SwigDelegateBuddy_0 swigDelegate0;
  private SwigDelegateBuddy_1 swigDelegate1;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] { typeof(OnBuddyEvSubStateParam) };
}
