//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CallSetting : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CallSetting(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CallSetting obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CallSetting obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CallSetting() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_CallSetting(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint flag {
    set {
      pjsua2PINVOKE.CallSetting_flag_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CallSetting_flag_get(swigCPtr);
      return ret;
    } 
  }

  public uint reqKeyframeMethod {
    set {
      pjsua2PINVOKE.CallSetting_reqKeyframeMethod_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CallSetting_reqKeyframeMethod_get(swigCPtr);
      return ret;
    } 
  }

  public uint audioCount {
    set {
      pjsua2PINVOKE.CallSetting_audioCount_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CallSetting_audioCount_get(swigCPtr);
      return ret;
    } 
  }

  public uint videoCount {
    set {
      pjsua2PINVOKE.CallSetting_videoCount_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CallSetting_videoCount_get(swigCPtr);
      return ret;
    } 
  }

  public IntVector mediaDir {
    set {
      pjsua2PINVOKE.CallSetting_mediaDir_set(swigCPtr, IntVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pjsua2PINVOKE.CallSetting_mediaDir_get(swigCPtr);
      IntVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new IntVector(cPtr, false);
      return ret;
    } 
  }

  public CallSetting(bool useDefaultValues) : this(pjsua2PINVOKE.new_CallSetting__SWIG_0(useDefaultValues), true) {
  }

  public CallSetting() : this(pjsua2PINVOKE.new_CallSetting__SWIG_1(), true) {
  }

  public bool isEmpty() {
    bool ret = pjsua2PINVOKE.CallSetting_isEmpty(swigCPtr);
    return ret;
  }

}
