//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CodecParamInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CodecParamInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CodecParamInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CodecParamInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CodecParamInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_CodecParamInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint clockRate {
    set {
      pjsua2PINVOKE.CodecParamInfo_clockRate_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CodecParamInfo_clockRate_get(swigCPtr);
      return ret;
    } 
  }

  public uint channelCnt {
    set {
      pjsua2PINVOKE.CodecParamInfo_channelCnt_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CodecParamInfo_channelCnt_get(swigCPtr);
      return ret;
    } 
  }

  public uint avgBps {
    set {
      pjsua2PINVOKE.CodecParamInfo_avgBps_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CodecParamInfo_avgBps_get(swigCPtr);
      return ret;
    } 
  }

  public uint maxBps {
    set {
      pjsua2PINVOKE.CodecParamInfo_maxBps_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CodecParamInfo_maxBps_get(swigCPtr);
      return ret;
    } 
  }

  public uint maxRxFrameSize {
    set {
      pjsua2PINVOKE.CodecParamInfo_maxRxFrameSize_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CodecParamInfo_maxRxFrameSize_get(swigCPtr);
      return ret;
    } 
  }

  public uint frameLen {
    set {
      pjsua2PINVOKE.CodecParamInfo_frameLen_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CodecParamInfo_frameLen_get(swigCPtr);
      return ret;
    } 
  }

  public uint frameLenDenum {
    set {
      pjsua2PINVOKE.CodecParamInfo_frameLenDenum_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CodecParamInfo_frameLenDenum_get(swigCPtr);
      return ret;
    } 
  }

  public uint encFrameLen {
    set {
      pjsua2PINVOKE.CodecParamInfo_encFrameLen_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CodecParamInfo_encFrameLen_get(swigCPtr);
      return ret;
    } 
  }

  public uint encFrameLenDenum {
    set {
      pjsua2PINVOKE.CodecParamInfo_encFrameLenDenum_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CodecParamInfo_encFrameLenDenum_get(swigCPtr);
      return ret;
    } 
  }

  public uint pcmBitsPerSample {
    set {
      pjsua2PINVOKE.CodecParamInfo_pcmBitsPerSample_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CodecParamInfo_pcmBitsPerSample_get(swigCPtr);
      return ret;
    } 
  }

  public uint pt {
    set {
      pjsua2PINVOKE.CodecParamInfo_pt_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CodecParamInfo_pt_get(swigCPtr);
      return ret;
    } 
  }

  public pjmedia_format_id fmtId {
    set {
      pjsua2PINVOKE.CodecParamInfo_fmtId_set(swigCPtr, (int)value);
    } 
    get {
      pjmedia_format_id ret = (pjmedia_format_id)pjsua2PINVOKE.CodecParamInfo_fmtId_get(swigCPtr);
      return ret;
    } 
  }

  public CodecParamInfo() : this(pjsua2PINVOKE.new_CodecParamInfo(), true) {
  }

}
