//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class OnDtmfEventParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OnDtmfEventParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OnDtmfEventParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(OnDtmfEventParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~OnDtmfEventParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_OnDtmfEventParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public pjsua_dtmf_method method {
    set {
      pjsua2PINVOKE.OnDtmfEventParam_method_set(swigCPtr, (int)value);
    } 
    get {
      pjsua_dtmf_method ret = (pjsua_dtmf_method)pjsua2PINVOKE.OnDtmfEventParam_method_get(swigCPtr);
      return ret;
    } 
  }

  public uint timestamp {
    set {
      pjsua2PINVOKE.OnDtmfEventParam_timestamp_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.OnDtmfEventParam_timestamp_get(swigCPtr);
      return ret;
    } 
  }

  public string digit {
    set {
      pjsua2PINVOKE.OnDtmfEventParam_digit_set(swigCPtr, value);
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = pjsua2PINVOKE.OnDtmfEventParam_digit_get(swigCPtr);
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public uint duration {
    set {
      pjsua2PINVOKE.OnDtmfEventParam_duration_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.OnDtmfEventParam_duration_get(swigCPtr);
      return ret;
    } 
  }

  public uint flags {
    set {
      pjsua2PINVOKE.OnDtmfEventParam_flags_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.OnDtmfEventParam_flags_get(swigCPtr);
      return ret;
    } 
  }

  public OnDtmfEventParam() : this(pjsua2PINVOKE.new_OnDtmfEventParam(), true) {
  }

}
