//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjmedia_vid_packing {
  PJMEDIA_VID_PACKING_UNKNOWN,
  PJMEDIA_VID_PACKING_PACKETS = 1,
  PJMEDIA_VID_PACKING_WHOLE = 2
}
