//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjmedia_srtp_keying_method {
  PJMEDIA_SRTP_KEYING_SDES,
  PJMEDIA_SRTP_KEYING_DTLS_SRTP,
  PJMEDIA_SRTP_KEYINGS_COUNT
}
