//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjmedia_vid_dev_fullscreen_flag {
  PJMEDIA_VID_DEV_WINDOWED = 0,
  PJMEDIA_VID_DEV_FULLSCREEN = 1,
  PJMEDIA_VID_DEV_FULLSCREEN_DESKTOP = 2
}
