//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjmedia_echo_flag {
  PJMEDIA_ECHO_DEFAULT = 0,
  PJMEDIA_ECHO_SPEEX = 1,
  PJMEDIA_ECHO_SIMPLE = 2,
  PJMEDIA_ECHO_WEBRTC = 3,
  PJMEDIA_ECHO_WEBRTC_AEC3 = 4,
  PJMEDIA_ECHO_ALGO_MASK = 15,
  PJMEDIA_ECHO_NO_LOCK = 16,
  PJMEDIA_ECHO_USE_SIMPLE_FIFO = 32,
  PJMEDIA_ECHO_USE_SW_ECHO = 64,
  PJMEDIA_ECHO_USE_NOISE_SUPPRESSOR = 128,
  PJMEDIA_ECHO_USE_GAIN_CONTROLLER = 256,
  PJMEDIA_ECHO_AGGRESSIVENESS_DEFAULT = 0,
  PJMEDIA_ECHO_AGGRESSIVENESS_CONSERVATIVE = 0x1000,
  PJMEDIA_ECHO_AGGRESSIVENESS_MODERATE = 0x2000,
  PJMEDIA_ECHO_AGGRESSIVENESS_AGGRESSIVE = 0x3000,
  PJMEDIA_ECHO_AGGRESSIVENESS_MASK = 0xF000
}
