//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjmedia_file_writer_option {
  PJMEDIA_FILE_WRITE_PCM = 0,
  PJMEDIA_FILE_WRITE_ALAW = 1,
  PJMEDIA_FILE_WRITE_ULAW = 2
}
