//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjmedia_frame_type {
  PJMEDIA_FRAME_TYPE_NONE,
  PJMEDIA_FRAME_TYPE_AUDIO,
  PJMEDIA_FRAME_TYPE_EXTENDED,
  PJMEDIA_FRAME_TYPE_VIDEO
}
