//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsip_evsub_state {
  PJSIP_EVSUB_STATE_NULL,
  PJSIP_EVSUB_STATE_SENT,
  PJSIP_EVSUB_STATE_ACCEPTED,
  PJSIP_EVSUB_STATE_PENDING,
  PJSIP_EVSUB_STATE_ACTIVE,
  PJSIP_EVSUB_STATE_TERMINATED,
  PJSIP_EVSUB_STATE_UNKNOWN
}
