//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsua_snd_dev_id {
  PJSUA_SND_DEFAULT_CAPTURE_DEV = -1,
  PJSUA_SND_DEFAULT_PLAYBACK_DEV = -2,
  PJSUA_SND_NO_DEV = -3,
  PJSUA_SND_NULL_DEV = -99
}
