//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsua_ipv6_use {
  PJSUA_IPV6_DISABLED,
  PJSUA_IPV6_ENABLED = 1,
  PJSUA_IPV6_ENABLED_NO_PREFERENCE = 1,
  PJSUA_IPV6_ENABLED_PREFER_IPV4,
  PJSUA_IPV6_ENABLED_PREFER_IPV6,
  PJSUA_IPV6_ENABLED_USE_IPV6_ONLY
}
