//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsua_100rel_use {
  PJSUA_100REL_NOT_USED,
  PJSUA_100REL_MANDATORY,
  PJSUA_100REL_OPTIONAL
}
